# Generated by Django 6.0.3 on 2026-03-24 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('material_type', models.CharField(choices=[('audio_only', 'Audio Only'), ('audio_image', 'Audio + Image'), ('text_only', 'Text Only'), ('text_image', 'Text + Image'), ('image_only', 'Image Only'), ('mixed', 'Mixed')], max_length=20)),
                ('display_type', models.CharField(choices=[('single', 'Single Question Material'), ('group', 'Grouped Questions Material')], default='single', max_length=20)),
                ('start_number', models.PositiveIntegerField(blank=True, null=True)),
                ('end_number', models.PositiveIntegerField(blank=True, null=True)),
                ('content_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topik/materials/images/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='topik/materials/audio/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=1)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('instruction', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['exam', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopikExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('level', models.CharField(choices=[('TOPIK_I', 'TOPIK I'), ('TOPIK_II', 'TOPIK II')], default='TOPIK_I', max_length=20)),
                ('exam_type', models.CharField(choices=[('real', 'Real Test'), ('mock', 'Mock Test'), ('practice', 'Practice Test')], default='practice', max_length=20)),
                ('exam_number', models.PositiveIntegerField(blank=True, help_text='e.g. 91', null=True)),
                ('paper_variant', models.CharField(blank=True, help_text='e.g. A, B', max_length=20)),
                ('title_ko', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-exam_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.PositiveIntegerField(default=0)),
                ('listening_score', models.PositiveIntegerField(default=0)),
                ('reading_score', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topik_attempts', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='topik.topikexam')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_number', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq_single', 'Multiple Choice - Single Answer'), ('true_false', 'True / False'), ('matching', 'Matching'), ('ordering', 'Ordering'), ('short_answer', 'Short Answer')], default='mcq_single', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topik/questions/images/')),
                ('score', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('correct_text_answer', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='topik.exammaterial')),
            ],
            options={
                'ordering': ['question_number', 'order', 'id'],
                'unique_together': {('material', 'order'), ('material', 'question_number')},
            },
        ),
        migrations.AddField(
            model_name='exammaterial',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='topik.examsection'),
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text='A, B, C, D or ① ② ③ ④', max_length=10)),
                ('choice_text', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='topik/choices/images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='topik.examquestion')),
            ],
            options={
                'ordering': ['question', 'order', 'id'],
                'unique_together': {('question', 'label'), ('question', 'order')},
            },
        ),
        migrations.AddField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='topik.topikexam'),
        ),
        migrations.AlterUniqueTogether(
            name='exammaterial',
            unique_together={('section', 'order')},
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.CharField(blank=True, max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_awarded', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='topik.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='topik.examquestion')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_in_answers', to='topik.questionchoice')),
            ],
            options={
                'ordering': ['question__question_number'],
                'unique_together': {('attempt', 'question')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examsection',
            unique_together={('exam', 'name')},
        ),
    ]
