# Generated by Django 6.0.3 on 2026-03-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammaterial',
            name='audio_file',
        ),
        migrations.AddField(
            model_name='examsection',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='topik/sections/audio/'),
        ),
    ]
