# Generated by Django 6.0.3 on 2026-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0002_remove_exammaterial_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
