# Generated by Django 6.0.3 on 2026-03-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0004_examattempt_copy_attempt_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topikexam',
            name='exam_mode',
            field=models.CharField(choices=[('full', 'Full Mock'), ('reading_only', 'Reading Only'), ('listening_only', 'Listening Only'), ('writing_only', 'Writing Only'), ('speaking_only', 'Speaking Only')], default='full', max_length=20),
        ),
    ]
