# Generated by Django 6.0.3 on 2026-03-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0005_topikexam_exam_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='current_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_attempts', to='topik.examsection'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='current_section_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
