# Generated by Django 6.0.3 on 2026-03-30 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0006_examattempt_current_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_number', models.PositiveIntegerField(help_text='Example: 51,52,53,54')),
                ('task_type', models.CharField(choices=[('gap_fill', 'Gap fill (51-52)'), ('graph_writing', 'Graph writing (53)'), ('essay', 'Essay (54)')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('instruction', models.TextField(blank=True)),
                ('prompt', models.TextField(help_text='Main writing questions/prompt')),
                ('image', models.ImageField(blank=True, null=True, upload_to='topik/writing/tasks')),
                ('min_words', models.PositiveIntegerField(blank=True, default=0)),
                ('max_words', models.PositiveIntegerField(blank=True, default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(limit_choices_to={'name': 'writing'}, on_delete=django.db.models.deletion.CASCADE, related_name='writing_tasks', to='topik.examsection')),
            ],
            options={
                'ordering': ['task_number', 'order'],
                'unique_together': {('section', 'order'), ('section', 'task_number')},
            },
        ),
        migrations.CreateModel(
            name='WritingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_text', models.TextField(blank=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('score_awarded', models.PositiveIntegerField(default=0)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_submissions', to='topik.examattempt')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='topik.writingtask')),
            ],
            options={
                'ordering': ['task__task_number'],
                'unique_together': {('attempt', 'task')},
            },
        ),
        migrations.CreateModel(
            name='WritingTaskBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blank_order', models.PositiveIntegerField(default=1)),
                ('answer_label', models.CharField(blank=True, help_text='Example:Blank 1', max_length=20)),
                ('correct_answer', models.CharField(max_length=250)),
                ('task', models.ForeignKey(limit_choices_to={'task_type': 'gap_fill'}, on_delete=django.db.models.deletion.CASCADE, related_name='blanks', to='topik.writingtask')),
            ],
            options={
                'ordering': ['blank_order'],
                'unique_together': {('task', 'blank_order')},
            },
        ),
    ]
