# Generated by Django 6.0.3 on 2026-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0007_writingtask_writingsubmission_writingtaskblank'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='writing_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
