# Generated by Django 6.0.3 on 2026-03-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topik', '0008_examattempt_writing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingtaskblank',
            name='scoring_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='writingtaskblank',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
