# Generated by Django 6.0.3 on 2026-04-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='ai_used_today',
            new_name='ai_used',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='tests_used_today',
            new_name='tests_used',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
