# Generated by Django 6.0.3 on 2026-03-18 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReadingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_image', models.ImageField(blank=True, null=True, upload_to='reading/diagrams/')),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField()),
                ('group_type', models.CharField(choices=[('TFNG', 'True False Not Given'), ('YESNO', 'Yes No Not Given'), ('MCQ_SINGLE', 'Multiple Choice (Single)'), ('MCQ_MULTI', 'Multiple Choice (Multiple)'), ('MATCH_HEADING', 'Matching Headings'), ('MATCH_INFO', 'Matching Information'), ('MATCH_FEATURE', 'Matching Features'), ('MATCH_ENDING', 'Matching Sentence Endings'), ('SUMMARY_BANK', 'Summary With Word Bank'), ('SUMMARY_NO_BANK', 'Summary Without Word Bank'), ('SENTENCE', 'Sentence Completion'), ('NOTE', 'Note Completion'), ('FORM', 'Form Completion'), ('DIAGRAM', 'Diagram Completion'), ('TABLE', 'Table Completion'), ('FLOW', 'Flowchart Completion'), ('SHORT', 'Short Answer'), ('LIST', 'List Selection')], max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='ielts.passage')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='ielts.questiongroup')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='ielts.question')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_options', to='ielts.questiongroup')),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='ielts.readingtest'),
        ),
    ]
