# Generated by Django 6.0.3 on 2026-03-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0002_alter_questiongroup_options_userreadingtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingtest',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
