# Generated by Django 6.0.3 on 2026-03-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0003_readingtest_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingtest',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='passage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
