# Generated by Django 6.0.3 on 2026-03-19 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0004_remove_readingtest_subtitle_passage_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='ielts.passage')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
