# Generated by Django 6.0.3 on 2026-03-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0005_paragraph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
