# Generated by Django 6.0.3 on 2026-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0006_alter_passage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='label',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
