# Generated by Django 6.0.3 on 2026-03-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0007_alter_paragraph_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
