# Generated by Django 6.0.3 on 2026-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0008_alter_paragraph_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
