# Generated by Django 6.0.3 on 2026-03-24 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0010_listeninggroup_listeningoption_listeningquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeninggroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listening/diagrams/'),
        ),
    ]
