# Generated by Django 6.0.3 on 2026-03-24 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0011_listeninggroup_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWritingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1_answer', models.TextField(blank=True)),
                ('task2_answer', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ielts.writingtest')),
            ],
            options={
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='WritingTask2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task2', to='ielts.writingtest')),
            ],
        ),
        migrations.CreateModel(
            name='WritingTask1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='writing/task1/')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task1', to='ielts.writingtest')),
            ],
        ),
        migrations.CreateModel(
            name='WritingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task1_task', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task1_coherence', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task1_lexical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task1_grammar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_task', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_coherence', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_lexical', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_grammar', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task1_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('task2_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('final_band', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('checked', 'Checked')], default='submitted', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ielts.userwritingtest')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ielts.writingtest')),
            ],
        ),
    ]
