# Generated by Django 6.0.3 on 2026-03-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0013_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Boost your IELTS score 🚀', max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
