# Generated by Django 6.0.3 on 2026-03-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0015_speakingquestion_speakingtest_speakingattempt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingattempt',
            name='question',
        ),
        migrations.AddField(
            model_name='speakingattempt',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ielts.speakingtest'),
            preserve_default=False,
        ),
    ]
