# Generated by Django 6.0.3 on 2026-03-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0017_speakingattempt_question_userspeakingtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingtest',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
