# Generated by Django 6.0.3 on 2026-03-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0018_speakingtest_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='writingresult',
            name='advanced',
            field=models.TextField(blank=True, null=True),
        ),
    ]
