# Generated by Django 6.0.3 on 2026-03-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0019_writingresult_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreadingtest',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userreadingtest',
            name='mistake_stats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
