# Generated by Django 6.0.3 on 2026-03-30 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0020_userreadingtest_accuracy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingAIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.IntegerField(default=0)),
                ('avg_score', models.FloatField(default=0)),
                ('avg_accuracy', models.FloatField(default=0)),
                ('weak_types', models.JSONField(default=dict)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_ai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
