# Generated by Django 6.0.3 on 2026-03-31 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0022_userlisteningtest_accuracy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='requests_used',
            new_name='ai_used_today',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='tokens_used',
            new_name='tests_used_today',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_reset',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PRO', 'Pro')], default='FREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
