# Generated by Django 6.0.3 on 2026-04-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0023_rename_requests_used_subscription_ai_used_today_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
