# Generated by Django 6.0.3 on 2026-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0024_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to='resources/')),
                ('image', models.ImageField(upload_to='resources/images/')),
                ('type', models.CharField(choices=[('book', 'Book'), ('magazine', 'Magazine'), ('newspaper', 'Newspaper')], max_length=20)),
            ],
        ),
    ]
