# Generated by Django 6.0.3 on 2026-04-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0025_resource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
